### ISSUE TITLE
Support multiple basic_auth statements in caddy2

### ISSUE THREAD

**Issue by klzgrad** [caddyserver/forwardproxy#81]
https://github.com/caddyserver/forwardproxy/blob/8d6f47b4c4f3bdbecba34d9f65c8c5629ca0a5b3/forwardproxy.go#L729-L732

Multiple basic_auth statements are not supported because it was not clear what json structure you wanted for doing it @mholt.

Some users are complaining https://github.com/klzgrad/naiveproxy/issues/137.

**Comment by mholt** [comment]
Sure, that's something that can be added I'm pretty sure.

**Comment by klzgrad** [comment]
I can add it but what json structure you want for doing this?

**Comment by klzgrad** [comment]
Hi @mholt, can you choose one json format for multiple basicauths from below so I can start making a PR?

1.
```json
"basicauths": [
  {"user": "me", "password": "hunter"}
]
```

2.
```json
"users": ["me"],
"passwords": ["hunter"],
```

3.
```json
"basicauths": [
  ["me", "hunter"]
]
```

**Comment by wiserain** [comment]
One more choice for your reference:

In traefik, users can configure multiple basicauths in a list. Below is an example of toml format used in traefik.

```toml
# Declaring the user list
[http.middlewares]
  [http.middlewares.test-auth.basicAuth]
    users = [
      "test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/", 
      "test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0",
    ]
```

I don't know implementation details but would be nice to use hashed passwords in conf, which is safe to expose in a plain text.

Thanks.
